version: "3.8"

services:
  app:
    build: .
    ports:
      - "5173:5173"  # Frontend (Vite)
      - "5000:5000"  # Backend (Express)
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
